version: '2'
services:
  wallet:
    image: buzzkillb/denarius-wallet:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: denarius-wallet
    volumes_from:
    - wallet-data
    environment:
      - ENABLE_WEB_VIEW=yes
      - DISPLAY=unix$DISPLAY
      - DEBUG=yes
    network_mode: host
    # ports:
    #  - "10000:10000"
  wallet-data:
    image: buzzkillb/denarius-wallet:latest
    container_name: wallet-data
    volumes:
    -  /tmp/.X11-unix:/tmp/.X11-unix
    - /etc/localtime:/etc/localtime:ro
    - ~/.denarius:/root/.denarius
    command: /bin/true
